language: php
php:
  - '5.3.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - chmod 777 -R ./
  - php -m

script:
  - find ./ -type f -print0 | while read -d $'\0' file; do if [ "${file##*.}" = "php" ]; then echo "Check $file"; php -l $file; echo "";  echo ""; fi; done
  - php test.php